// <auto-generated />
using System;
using AmarTools.Bankcheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmarTools.Bankcheck.Migrations
{
    [DbContext(typeof(ChequeDbContext))]
    partial class ChequeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmarTools.Bankcheck.Models.ChequeLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChequeTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<float>("FontSize")
                        .HasColumnType("real");

                    b.Property<string>("FontStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ChequeTemplateId");

                    b.ToTable("ChequeLayouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChequeTemplateId = 1,
                            FieldName = "Payee",
                            FontColor = "#000000",
                            FontSize = 11f,
                            FontStyle = "Normal",
                            MaxLength = 100,
                            X = 140f,
                            Y = 185f
                        },
                        new
                        {
                            Id = 2,
                            ChequeTemplateId = 1,
                            FieldName = "Amount",
                            FontColor = "#000000",
                            FontSize = 11f,
                            FontStyle = "Bold",
                            MaxLength = 20,
                            X = 660f,
                            Y = 185f
                        },
                        new
                        {
                            Id = 3,
                            ChequeTemplateId = 1,
                            FieldName = "AmountWords",
                            FontColor = "#000000",
                            FontSize = 10f,
                            FontStyle = "Normal",
                            MaxLength = 200,
                            X = 90f,
                            Y = 155f
                        },
                        new
                        {
                            Id = 4,
                            ChequeTemplateId = 1,
                            FieldName = "Date",
                            FontColor = "#000000",
                            FontSize = 10f,
                            FontStyle = "Normal",
                            MaxLength = 20,
                            X = 660f,
                            Y = 240f
                        },
                        new
                        {
                            Id = 5,
                            ChequeTemplateId = 1,
                            FieldName = "ChequeNo",
                            FontColor = "#555555",
                            FontSize = 9f,
                            FontStyle = "Normal",
                            MaxLength = 30,
                            X = 90f,
                            Y = 55f
                        });
                });

            modelBuilder.Entity("AmarTools.Bankcheck.Models.ChequeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChequeImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("PageHeight")
                        .HasColumnType("real");

                    b.Property<float>("PageWidth")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ChequeTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "1234567890",
                            BankName = "City Bank",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PageHeight = 300f,
                            PageWidth = 842f
                        });
                });

            modelBuilder.Entity("AmarTools.Bankcheck.Models.PrintedCheque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ChequeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChequeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ChequeTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("MemoNote")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PrintedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrintedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChequeTemplateId");

                    b.ToTable("PrintedCheques");
                });

            modelBuilder.Entity("AmarTools.Bankcheck.Models.ChequeLayout", b =>
                {
                    b.HasOne("AmarTools.Bankcheck.Models.ChequeTemplate", "ChequeTemplate")
                        .WithMany("Layouts")
                        .HasForeignKey("ChequeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChequeTemplate");
                });

            modelBuilder.Entity("AmarTools.Bankcheck.Models.PrintedCheque", b =>
                {
                    b.HasOne("AmarTools.Bankcheck.Models.ChequeTemplate", "ChequeTemplate")
                        .WithMany("PrintedCheques")
                        .HasForeignKey("ChequeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChequeTemplate");
                });

            modelBuilder.Entity("AmarTools.Bankcheck.Models.ChequeTemplate", b =>
                {
                    b.Navigation("Layouts");

                    b.Navigation("PrintedCheques");
                });
#pragma warning restore 612, 618
        }
    }
}
